---
title: "“COMPSCIX 415.2 Homework 1”"
output: 
  html_document: 
    theme: cerulean
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
`My Github repository for my assignments can be found at this URL [https://github.com/phillipmanning/compscix-415-2-assignments.git](https://github.com/phillipmanning/compscix-415-2-assignments.git
                                                                   
```{r load_packages, warning=FALSE, message=FALSE} 
``` 
   
   ```data("WorldCities")
   glimpse(WorldCities)
   WorldCities <- head(WorldCities, 200) # 200 rows
   country_col <- WorldCities$country
   unique(country_col)
   ```
                                                                                                                                     
                                                                                                                                     
                                                                                                                                     
                                                                                                                                     
                                                                                                                                     
                                                                                                                                     